# Generated by Django 4.1.7 on 2023-02-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.BinaryField(default=b''),
        ),
    ]
